//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace log4om.log4omService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Log", Namespace="http//Log4OMNG/BE", ItemName="QSO")]
    [System.SerializableAttribute()]
    public class Log : System.Collections.Generic.List<log4om.log4omService.QSO> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QSO", Namespace="http//Log4OMNG/BE")]
    [System.SerializableAttribute()]
    public partial class QSO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private log4om.log4omService.QsoAction ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AntAzField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AntElField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AntPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArrlCheckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArrlSectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AwardGrantedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AwardSubmittedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BandRxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallsignUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClubLogQsoUploadDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClubLogQsoUploadStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CntyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactedOpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ContestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CqzField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditGrantedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditSubmittedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DirtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DxccField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EqCallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EqslQslRcvdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EqslQslSentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EqslQslrdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EqslQslsdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EqslUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FistsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FistsCcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ForceInitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FreqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FreqRxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GridsquareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomepageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HrdlogQsoUploadDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HrdlogQsoUploadStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IotaIslandIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItuzField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LotwQslRcvdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LotwQslSentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LotwQslrdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LotwQslsdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LotwUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ManualDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxBurstsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsShowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MyAntennaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MyCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MyCntyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MyCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MyCqZoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MyFistsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MyGridsquareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MyIotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MyIotaIslandIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MyItuZoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MyLatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MyLonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MyPostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MyRigField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MySigField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MySigInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MySotaRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MyStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MyStreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MyUsacaCountiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MyVuccGridsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NrBurstsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NrPingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerCallsignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PfxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PortableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrecedenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramversionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublicKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool QrpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QrzcomQsoUploadDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QrzcomQsoUploadStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QslRcvdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QslRcvdViaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QslSentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QslSentViaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool QslUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QslViaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QslmsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QslrdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QslsdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QsoAwardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QsoCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QsoDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QsoDateOffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long QsoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QsoRandomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RigField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RstRcvdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RstSentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RxPwrDecimalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SatModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SatNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SfiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SigField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SigInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkccField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SotaRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SrxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SrxStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StationCallsignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StxStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubmissionStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SwlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TenTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TheClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TheOperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeOffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TxPwrDecimalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsacaCountiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValidatedCallsignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VuccGridsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AIndex {
            get {
                return this.AIndexField;
            }
            set {
                if ((this.AIndexField.Equals(value) != true)) {
                    this.AIndexField = value;
                    this.RaisePropertyChanged("AIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public log4om.log4omService.QsoAction Action {
            get {
                return this.ActionField;
            }
            set {
                if ((this.ActionField.Equals(value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Age {
            get {
                return this.AgeField;
            }
            set {
                if ((object.ReferenceEquals(this.AgeField, value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AntAz {
            get {
                return this.AntAzField;
            }
            set {
                if ((this.AntAzField.Equals(value) != true)) {
                    this.AntAzField = value;
                    this.RaisePropertyChanged("AntAz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AntEl {
            get {
                return this.AntElField;
            }
            set {
                if ((this.AntElField.Equals(value) != true)) {
                    this.AntElField = value;
                    this.RaisePropertyChanged("AntEl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AntPath {
            get {
                return this.AntPathField;
            }
            set {
                if ((object.ReferenceEquals(this.AntPathField, value) != true)) {
                    this.AntPathField = value;
                    this.RaisePropertyChanged("AntPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArrlCheck {
            get {
                return this.ArrlCheckField;
            }
            set {
                if ((object.ReferenceEquals(this.ArrlCheckField, value) != true)) {
                    this.ArrlCheckField = value;
                    this.RaisePropertyChanged("ArrlCheck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArrlSect {
            get {
                return this.ArrlSectField;
            }
            set {
                if ((object.ReferenceEquals(this.ArrlSectField, value) != true)) {
                    this.ArrlSectField = value;
                    this.RaisePropertyChanged("ArrlSect");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AwardGranted {
            get {
                return this.AwardGrantedField;
            }
            set {
                if ((object.ReferenceEquals(this.AwardGrantedField, value) != true)) {
                    this.AwardGrantedField = value;
                    this.RaisePropertyChanged("AwardGranted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AwardSubmitted {
            get {
                return this.AwardSubmittedField;
            }
            set {
                if ((object.ReferenceEquals(this.AwardSubmittedField, value) != true)) {
                    this.AwardSubmittedField = value;
                    this.RaisePropertyChanged("AwardSubmitted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Band {
            get {
                return this.BandField;
            }
            set {
                if ((object.ReferenceEquals(this.BandField, value) != true)) {
                    this.BandField = value;
                    this.RaisePropertyChanged("Band");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BandRx {
            get {
                return this.BandRxField;
            }
            set {
                if ((object.ReferenceEquals(this.BandRxField, value) != true)) {
                    this.BandRxField = value;
                    this.RaisePropertyChanged("BandRx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Call {
            get {
                return this.CallField;
            }
            set {
                if ((object.ReferenceEquals(this.CallField, value) != true)) {
                    this.CallField = value;
                    this.RaisePropertyChanged("Call");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallsignUrl {
            get {
                return this.CallsignUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.CallsignUrlField, value) != true)) {
                    this.CallsignUrlField = value;
                    this.RaisePropertyChanged("CallsignUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClubLogQsoUploadDate {
            get {
                return this.ClubLogQsoUploadDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubLogQsoUploadDateField, value) != true)) {
                    this.ClubLogQsoUploadDateField = value;
                    this.RaisePropertyChanged("ClubLogQsoUploadDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClubLogQsoUploadStatus {
            get {
                return this.ClubLogQsoUploadStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubLogQsoUploadStatusField, value) != true)) {
                    this.ClubLogQsoUploadStatusField = value;
                    this.RaisePropertyChanged("ClubLogQsoUploadStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cnty {
            get {
                return this.CntyField;
            }
            set {
                if ((object.ReferenceEquals(this.CntyField, value) != true)) {
                    this.CntyField = value;
                    this.RaisePropertyChanged("Cnty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cont {
            get {
                return this.ContField;
            }
            set {
                if ((object.ReferenceEquals(this.ContField, value) != true)) {
                    this.ContField = value;
                    this.RaisePropertyChanged("Cont");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactedOp {
            get {
                return this.ContactedOpField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactedOpField, value) != true)) {
                    this.ContactedOpField = value;
                    this.RaisePropertyChanged("ContactedOp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Contest {
            get {
                return this.ContestField;
            }
            set {
                if ((this.ContestField.Equals(value) != true)) {
                    this.ContestField = value;
                    this.RaisePropertyChanged("Contest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContestId {
            get {
                return this.ContestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ContestIdField, value) != true)) {
                    this.ContestIdField = value;
                    this.RaisePropertyChanged("ContestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cqz {
            get {
                return this.CqzField;
            }
            set {
                if ((this.CqzField.Equals(value) != true)) {
                    this.CqzField = value;
                    this.RaisePropertyChanged("Cqz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditGranted {
            get {
                return this.CreditGrantedField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditGrantedField, value) != true)) {
                    this.CreditGrantedField = value;
                    this.RaisePropertyChanged("CreditGranted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditSubmitted {
            get {
                return this.CreditSubmittedField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditSubmittedField, value) != true)) {
                    this.CreditSubmittedField = value;
                    this.RaisePropertyChanged("CreditSubmitted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Dirty {
            get {
                return this.DirtyField;
            }
            set {
                if ((this.DirtyField.Equals(value) != true)) {
                    this.DirtyField = value;
                    this.RaisePropertyChanged("Dirty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Distance {
            get {
                return this.DistanceField;
            }
            set {
                if ((this.DistanceField.Equals(value) != true)) {
                    this.DistanceField = value;
                    this.RaisePropertyChanged("Distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dxcc {
            get {
                return this.DxccField;
            }
            set {
                if ((object.ReferenceEquals(this.DxccField, value) != true)) {
                    this.DxccField = value;
                    this.RaisePropertyChanged("Dxcc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EqCall {
            get {
                return this.EqCallField;
            }
            set {
                if ((object.ReferenceEquals(this.EqCallField, value) != true)) {
                    this.EqCallField = value;
                    this.RaisePropertyChanged("EqCall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EqslQslRcvd {
            get {
                return this.EqslQslRcvdField;
            }
            set {
                if ((object.ReferenceEquals(this.EqslQslRcvdField, value) != true)) {
                    this.EqslQslRcvdField = value;
                    this.RaisePropertyChanged("EqslQslRcvd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EqslQslSent {
            get {
                return this.EqslQslSentField;
            }
            set {
                if ((object.ReferenceEquals(this.EqslQslSentField, value) != true)) {
                    this.EqslQslSentField = value;
                    this.RaisePropertyChanged("EqslQslSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EqslQslrdate {
            get {
                return this.EqslQslrdateField;
            }
            set {
                if ((object.ReferenceEquals(this.EqslQslrdateField, value) != true)) {
                    this.EqslQslrdateField = value;
                    this.RaisePropertyChanged("EqslQslrdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EqslQslsdate {
            get {
                return this.EqslQslsdateField;
            }
            set {
                if ((object.ReferenceEquals(this.EqslQslsdateField, value) != true)) {
                    this.EqslQslsdateField = value;
                    this.RaisePropertyChanged("EqslQslsdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EqslUser {
            get {
                return this.EqslUserField;
            }
            set {
                if ((this.EqslUserField.Equals(value) != true)) {
                    this.EqslUserField = value;
                    this.RaisePropertyChanged("EqslUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fists {
            get {
                return this.FistsField;
            }
            set {
                if ((object.ReferenceEquals(this.FistsField, value) != true)) {
                    this.FistsField = value;
                    this.RaisePropertyChanged("Fists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FistsCc {
            get {
                return this.FistsCcField;
            }
            set {
                if ((object.ReferenceEquals(this.FistsCcField, value) != true)) {
                    this.FistsCcField = value;
                    this.RaisePropertyChanged("FistsCc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ForceInit {
            get {
                return this.ForceInitField;
            }
            set {
                if ((this.ForceInitField.Equals(value) != true)) {
                    this.ForceInitField = value;
                    this.RaisePropertyChanged("ForceInit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Freq {
            get {
                return this.FreqField;
            }
            set {
                if ((object.ReferenceEquals(this.FreqField, value) != true)) {
                    this.FreqField = value;
                    this.RaisePropertyChanged("Freq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FreqRx {
            get {
                return this.FreqRxField;
            }
            set {
                if ((object.ReferenceEquals(this.FreqRxField, value) != true)) {
                    this.FreqRxField = value;
                    this.RaisePropertyChanged("FreqRx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gridsquare {
            get {
                return this.GridsquareField;
            }
            set {
                if ((object.ReferenceEquals(this.GridsquareField, value) != true)) {
                    this.GridsquareField = value;
                    this.RaisePropertyChanged("Gridsquare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomepageUrl {
            get {
                return this.HomepageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.HomepageUrlField, value) != true)) {
                    this.HomepageUrlField = value;
                    this.RaisePropertyChanged("HomepageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HrdlogQsoUploadDate {
            get {
                return this.HrdlogQsoUploadDateField;
            }
            set {
                if ((object.ReferenceEquals(this.HrdlogQsoUploadDateField, value) != true)) {
                    this.HrdlogQsoUploadDateField = value;
                    this.RaisePropertyChanged("HrdlogQsoUploadDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HrdlogQsoUploadStatus {
            get {
                return this.HrdlogQsoUploadStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.HrdlogQsoUploadStatusField, value) != true)) {
                    this.HrdlogQsoUploadStatusField = value;
                    this.RaisePropertyChanged("HrdlogQsoUploadStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Iota {
            get {
                return this.IotaField;
            }
            set {
                if ((object.ReferenceEquals(this.IotaField, value) != true)) {
                    this.IotaField = value;
                    this.RaisePropertyChanged("Iota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IotaIslandId {
            get {
                return this.IotaIslandIdField;
            }
            set {
                if ((object.ReferenceEquals(this.IotaIslandIdField, value) != true)) {
                    this.IotaIslandIdField = value;
                    this.RaisePropertyChanged("IotaIslandId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError {
            get {
                return this.IsErrorField;
            }
            set {
                if ((this.IsErrorField.Equals(value) != true)) {
                    this.IsErrorField = value;
                    this.RaisePropertyChanged("IsError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ituz {
            get {
                return this.ItuzField;
            }
            set {
                if ((this.ItuzField.Equals(value) != true)) {
                    this.ItuzField = value;
                    this.RaisePropertyChanged("Ituz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KIndex {
            get {
                return this.KIndexField;
            }
            set {
                if ((this.KIndexField.Equals(value) != true)) {
                    this.KIndexField = value;
                    this.RaisePropertyChanged("KIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lat {
            get {
                return this.LatField;
            }
            set {
                if ((object.ReferenceEquals(this.LatField, value) != true)) {
                    this.LatField = value;
                    this.RaisePropertyChanged("Lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lon {
            get {
                return this.LonField;
            }
            set {
                if ((object.ReferenceEquals(this.LonField, value) != true)) {
                    this.LonField = value;
                    this.RaisePropertyChanged("Lon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LotwQslRcvd {
            get {
                return this.LotwQslRcvdField;
            }
            set {
                if ((object.ReferenceEquals(this.LotwQslRcvdField, value) != true)) {
                    this.LotwQslRcvdField = value;
                    this.RaisePropertyChanged("LotwQslRcvd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LotwQslSent {
            get {
                return this.LotwQslSentField;
            }
            set {
                if ((object.ReferenceEquals(this.LotwQslSentField, value) != true)) {
                    this.LotwQslSentField = value;
                    this.RaisePropertyChanged("LotwQslSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LotwQslrdate {
            get {
                return this.LotwQslrdateField;
            }
            set {
                if ((object.ReferenceEquals(this.LotwQslrdateField, value) != true)) {
                    this.LotwQslrdateField = value;
                    this.RaisePropertyChanged("LotwQslrdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LotwQslsdate {
            get {
                return this.LotwQslsdateField;
            }
            set {
                if ((object.ReferenceEquals(this.LotwQslsdateField, value) != true)) {
                    this.LotwQslsdateField = value;
                    this.RaisePropertyChanged("LotwQslsdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LotwUser {
            get {
                return this.LotwUserField;
            }
            set {
                if ((this.LotwUserField.Equals(value) != true)) {
                    this.LotwUserField = value;
                    this.RaisePropertyChanged("LotwUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ManualDateTime {
            get {
                return this.ManualDateTimeField;
            }
            set {
                if ((this.ManualDateTimeField.Equals(value) != true)) {
                    this.ManualDateTimeField = value;
                    this.RaisePropertyChanged("ManualDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxBursts {
            get {
                return this.MaxBurstsField;
            }
            set {
                if ((this.MaxBurstsField.Equals(value) != true)) {
                    this.MaxBurstsField = value;
                    this.RaisePropertyChanged("MaxBursts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((this.MobileField.Equals(value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeField, value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsShower {
            get {
                return this.MsShowerField;
            }
            set {
                if ((object.ReferenceEquals(this.MsShowerField, value) != true)) {
                    this.MsShowerField = value;
                    this.RaisePropertyChanged("MsShower");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MyAntenna {
            get {
                return this.MyAntennaField;
            }
            set {
                if ((object.ReferenceEquals(this.MyAntennaField, value) != true)) {
                    this.MyAntennaField = value;
                    this.RaisePropertyChanged("MyAntenna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MyCity {
            get {
                return this.MyCityField;
            }
            set {
                if ((object.ReferenceEquals(this.MyCityField, value) != true)) {
                    this.MyCityField = value;
                    this.RaisePropertyChanged("MyCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MyCnty {
            get {
                return this.MyCntyField;
            }
            set {
                if ((object.ReferenceEquals(this.MyCntyField, value) != true)) {
                    this.MyCntyField = value;
                    this.RaisePropertyChanged("MyCnty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MyCountry {
            get {
                return this.MyCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.MyCountryField, value) != true)) {
                    this.MyCountryField = value;
                    this.RaisePropertyChanged("MyCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MyCqZone {
            get {
                return this.MyCqZoneField;
            }
            set {
                if ((this.MyCqZoneField.Equals(value) != true)) {
                    this.MyCqZoneField = value;
                    this.RaisePropertyChanged("MyCqZone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MyFists {
            get {
                return this.MyFistsField;
            }
            set {
                if ((object.ReferenceEquals(this.MyFistsField, value) != true)) {
                    this.MyFistsField = value;
                    this.RaisePropertyChanged("MyFists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MyGridsquare {
            get {
                return this.MyGridsquareField;
            }
            set {
                if ((object.ReferenceEquals(this.MyGridsquareField, value) != true)) {
                    this.MyGridsquareField = value;
                    this.RaisePropertyChanged("MyGridsquare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MyIota {
            get {
                return this.MyIotaField;
            }
            set {
                if ((object.ReferenceEquals(this.MyIotaField, value) != true)) {
                    this.MyIotaField = value;
                    this.RaisePropertyChanged("MyIota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MyIotaIslandId {
            get {
                return this.MyIotaIslandIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MyIotaIslandIdField, value) != true)) {
                    this.MyIotaIslandIdField = value;
                    this.RaisePropertyChanged("MyIotaIslandId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MyItuZone {
            get {
                return this.MyItuZoneField;
            }
            set {
                if ((this.MyItuZoneField.Equals(value) != true)) {
                    this.MyItuZoneField = value;
                    this.RaisePropertyChanged("MyItuZone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MyLat {
            get {
                return this.MyLatField;
            }
            set {
                if ((object.ReferenceEquals(this.MyLatField, value) != true)) {
                    this.MyLatField = value;
                    this.RaisePropertyChanged("MyLat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MyLon {
            get {
                return this.MyLonField;
            }
            set {
                if ((object.ReferenceEquals(this.MyLonField, value) != true)) {
                    this.MyLonField = value;
                    this.RaisePropertyChanged("MyLon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MyName {
            get {
                return this.MyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MyNameField, value) != true)) {
                    this.MyNameField = value;
                    this.RaisePropertyChanged("MyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MyPostalCode {
            get {
                return this.MyPostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MyPostalCodeField, value) != true)) {
                    this.MyPostalCodeField = value;
                    this.RaisePropertyChanged("MyPostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MyRig {
            get {
                return this.MyRigField;
            }
            set {
                if ((object.ReferenceEquals(this.MyRigField, value) != true)) {
                    this.MyRigField = value;
                    this.RaisePropertyChanged("MyRig");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MySig {
            get {
                return this.MySigField;
            }
            set {
                if ((object.ReferenceEquals(this.MySigField, value) != true)) {
                    this.MySigField = value;
                    this.RaisePropertyChanged("MySig");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MySigInfo {
            get {
                return this.MySigInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.MySigInfoField, value) != true)) {
                    this.MySigInfoField = value;
                    this.RaisePropertyChanged("MySigInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MySotaRef {
            get {
                return this.MySotaRefField;
            }
            set {
                if ((object.ReferenceEquals(this.MySotaRefField, value) != true)) {
                    this.MySotaRefField = value;
                    this.RaisePropertyChanged("MySotaRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MyState {
            get {
                return this.MyStateField;
            }
            set {
                if ((object.ReferenceEquals(this.MyStateField, value) != true)) {
                    this.MyStateField = value;
                    this.RaisePropertyChanged("MyState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MyStreet {
            get {
                return this.MyStreetField;
            }
            set {
                if ((object.ReferenceEquals(this.MyStreetField, value) != true)) {
                    this.MyStreetField = value;
                    this.RaisePropertyChanged("MyStreet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MyUsacaCounties {
            get {
                return this.MyUsacaCountiesField;
            }
            set {
                if ((object.ReferenceEquals(this.MyUsacaCountiesField, value) != true)) {
                    this.MyUsacaCountiesField = value;
                    this.RaisePropertyChanged("MyUsacaCounties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MyVuccGrids {
            get {
                return this.MyVuccGridsField;
            }
            set {
                if ((object.ReferenceEquals(this.MyVuccGridsField, value) != true)) {
                    this.MyVuccGridsField = value;
                    this.RaisePropertyChanged("MyVuccGrids");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NrBursts {
            get {
                return this.NrBurstsField;
            }
            set {
                if ((this.NrBurstsField.Equals(value) != true)) {
                    this.NrBurstsField = value;
                    this.RaisePropertyChanged("NrBursts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NrPings {
            get {
                return this.NrPingsField;
            }
            set {
                if ((this.NrPingsField.Equals(value) != true)) {
                    this.NrPingsField = value;
                    this.RaisePropertyChanged("NrPings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerCallsign {
            get {
                return this.OwnerCallsignField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerCallsignField, value) != true)) {
                    this.OwnerCallsignField = value;
                    this.RaisePropertyChanged("OwnerCallsign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pfx {
            get {
                return this.PfxField;
            }
            set {
                if ((object.ReferenceEquals(this.PfxField, value) != true)) {
                    this.PfxField = value;
                    this.RaisePropertyChanged("Pfx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Portable {
            get {
                return this.PortableField;
            }
            set {
                if ((this.PortableField.Equals(value) != true)) {
                    this.PortableField = value;
                    this.RaisePropertyChanged("Portable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Precedence {
            get {
                return this.PrecedenceField;
            }
            set {
                if ((object.ReferenceEquals(this.PrecedenceField, value) != true)) {
                    this.PrecedenceField = value;
                    this.RaisePropertyChanged("Precedence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Programid {
            get {
                return this.ProgramidField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramidField, value) != true)) {
                    this.ProgramidField = value;
                    this.RaisePropertyChanged("Programid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Programversion {
            get {
                return this.ProgramversionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramversionField, value) != true)) {
                    this.ProgramversionField = value;
                    this.RaisePropertyChanged("Programversion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropMode {
            get {
                return this.PropModeField;
            }
            set {
                if ((object.ReferenceEquals(this.PropModeField, value) != true)) {
                    this.PropModeField = value;
                    this.RaisePropertyChanged("PropMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublicKey {
            get {
                return this.PublicKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PublicKeyField, value) != true)) {
                    this.PublicKeyField = value;
                    this.RaisePropertyChanged("PublicKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Qrp {
            get {
                return this.QrpField;
            }
            set {
                if ((this.QrpField.Equals(value) != true)) {
                    this.QrpField = value;
                    this.RaisePropertyChanged("Qrp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QrzcomQsoUploadDate {
            get {
                return this.QrzcomQsoUploadDateField;
            }
            set {
                if ((object.ReferenceEquals(this.QrzcomQsoUploadDateField, value) != true)) {
                    this.QrzcomQsoUploadDateField = value;
                    this.RaisePropertyChanged("QrzcomQsoUploadDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QrzcomQsoUploadStatus {
            get {
                return this.QrzcomQsoUploadStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.QrzcomQsoUploadStatusField, value) != true)) {
                    this.QrzcomQsoUploadStatusField = value;
                    this.RaisePropertyChanged("QrzcomQsoUploadStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QslRcvd {
            get {
                return this.QslRcvdField;
            }
            set {
                if ((object.ReferenceEquals(this.QslRcvdField, value) != true)) {
                    this.QslRcvdField = value;
                    this.RaisePropertyChanged("QslRcvd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QslRcvdVia {
            get {
                return this.QslRcvdViaField;
            }
            set {
                if ((object.ReferenceEquals(this.QslRcvdViaField, value) != true)) {
                    this.QslRcvdViaField = value;
                    this.RaisePropertyChanged("QslRcvdVia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QslSent {
            get {
                return this.QslSentField;
            }
            set {
                if ((object.ReferenceEquals(this.QslSentField, value) != true)) {
                    this.QslSentField = value;
                    this.RaisePropertyChanged("QslSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QslSentVia {
            get {
                return this.QslSentViaField;
            }
            set {
                if ((object.ReferenceEquals(this.QslSentViaField, value) != true)) {
                    this.QslSentViaField = value;
                    this.RaisePropertyChanged("QslSentVia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool QslUser {
            get {
                return this.QslUserField;
            }
            set {
                if ((this.QslUserField.Equals(value) != true)) {
                    this.QslUserField = value;
                    this.RaisePropertyChanged("QslUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QslVia {
            get {
                return this.QslViaField;
            }
            set {
                if ((object.ReferenceEquals(this.QslViaField, value) != true)) {
                    this.QslViaField = value;
                    this.RaisePropertyChanged("QslVia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Qslmsg {
            get {
                return this.QslmsgField;
            }
            set {
                if ((object.ReferenceEquals(this.QslmsgField, value) != true)) {
                    this.QslmsgField = value;
                    this.RaisePropertyChanged("Qslmsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Qslrdate {
            get {
                return this.QslrdateField;
            }
            set {
                if ((object.ReferenceEquals(this.QslrdateField, value) != true)) {
                    this.QslrdateField = value;
                    this.RaisePropertyChanged("Qslrdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Qslsdate {
            get {
                return this.QslsdateField;
            }
            set {
                if ((object.ReferenceEquals(this.QslsdateField, value) != true)) {
                    this.QslsdateField = value;
                    this.RaisePropertyChanged("Qslsdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QsoAwards {
            get {
                return this.QsoAwardsField;
            }
            set {
                if ((object.ReferenceEquals(this.QsoAwardsField, value) != true)) {
                    this.QsoAwardsField = value;
                    this.RaisePropertyChanged("QsoAwards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QsoComplete {
            get {
                return this.QsoCompleteField;
            }
            set {
                if ((object.ReferenceEquals(this.QsoCompleteField, value) != true)) {
                    this.QsoCompleteField = value;
                    this.RaisePropertyChanged("QsoComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QsoDate {
            get {
                return this.QsoDateField;
            }
            set {
                if ((object.ReferenceEquals(this.QsoDateField, value) != true)) {
                    this.QsoDateField = value;
                    this.RaisePropertyChanged("QsoDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QsoDateOff {
            get {
                return this.QsoDateOffField;
            }
            set {
                if ((object.ReferenceEquals(this.QsoDateOffField, value) != true)) {
                    this.QsoDateOffField = value;
                    this.RaisePropertyChanged("QsoDateOff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long QsoId {
            get {
                return this.QsoIdField;
            }
            set {
                if ((this.QsoIdField.Equals(value) != true)) {
                    this.QsoIdField = value;
                    this.RaisePropertyChanged("QsoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QsoRandom {
            get {
                return this.QsoRandomField;
            }
            set {
                if ((object.ReferenceEquals(this.QsoRandomField, value) != true)) {
                    this.QsoRandomField = value;
                    this.RaisePropertyChanged("QsoRandom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Qth {
            get {
                return this.QthField;
            }
            set {
                if ((object.ReferenceEquals(this.QthField, value) != true)) {
                    this.QthField = value;
                    this.RaisePropertyChanged("Qth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rig {
            get {
                return this.RigField;
            }
            set {
                if ((object.ReferenceEquals(this.RigField, value) != true)) {
                    this.RigField = value;
                    this.RaisePropertyChanged("Rig");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RstRcvd {
            get {
                return this.RstRcvdField;
            }
            set {
                if ((object.ReferenceEquals(this.RstRcvdField, value) != true)) {
                    this.RstRcvdField = value;
                    this.RaisePropertyChanged("RstRcvd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RstSent {
            get {
                return this.RstSentField;
            }
            set {
                if ((object.ReferenceEquals(this.RstSentField, value) != true)) {
                    this.RstSentField = value;
                    this.RaisePropertyChanged("RstSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RxPwrDecimal {
            get {
                return this.RxPwrDecimalField;
            }
            set {
                if ((this.RxPwrDecimalField.Equals(value) != true)) {
                    this.RxPwrDecimalField = value;
                    this.RaisePropertyChanged("RxPwrDecimal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SatMode {
            get {
                return this.SatModeField;
            }
            set {
                if ((object.ReferenceEquals(this.SatModeField, value) != true)) {
                    this.SatModeField = value;
                    this.RaisePropertyChanged("SatMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SatName {
            get {
                return this.SatNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SatNameField, value) != true)) {
                    this.SatNameField = value;
                    this.RaisePropertyChanged("SatName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sfi {
            get {
                return this.SfiField;
            }
            set {
                if ((this.SfiField.Equals(value) != true)) {
                    this.SfiField = value;
                    this.RaisePropertyChanged("Sfi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sig {
            get {
                return this.SigField;
            }
            set {
                if ((object.ReferenceEquals(this.SigField, value) != true)) {
                    this.SigField = value;
                    this.RaisePropertyChanged("Sig");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SigInfo {
            get {
                return this.SigInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SigInfoField, value) != true)) {
                    this.SigInfoField = value;
                    this.RaisePropertyChanged("SigInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Skcc {
            get {
                return this.SkccField;
            }
            set {
                if ((object.ReferenceEquals(this.SkccField, value) != true)) {
                    this.SkccField = value;
                    this.RaisePropertyChanged("Skcc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SotaRef {
            get {
                return this.SotaRefField;
            }
            set {
                if ((object.ReferenceEquals(this.SotaRefField, value) != true)) {
                    this.SotaRefField = value;
                    this.RaisePropertyChanged("SotaRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Srx {
            get {
                return this.SrxField;
            }
            set {
                if ((object.ReferenceEquals(this.SrxField, value) != true)) {
                    this.SrxField = value;
                    this.RaisePropertyChanged("Srx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SrxString {
            get {
                return this.SrxStringField;
            }
            set {
                if ((object.ReferenceEquals(this.SrxStringField, value) != true)) {
                    this.SrxStringField = value;
                    this.RaisePropertyChanged("SrxString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StationCallsign {
            get {
                return this.StationCallsignField;
            }
            set {
                if ((object.ReferenceEquals(this.StationCallsignField, value) != true)) {
                    this.StationCallsignField = value;
                    this.RaisePropertyChanged("StationCallsign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stx {
            get {
                return this.StxField;
            }
            set {
                if ((object.ReferenceEquals(this.StxField, value) != true)) {
                    this.StxField = value;
                    this.RaisePropertyChanged("Stx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StxString {
            get {
                return this.StxStringField;
            }
            set {
                if ((object.ReferenceEquals(this.StxStringField, value) != true)) {
                    this.StxStringField = value;
                    this.RaisePropertyChanged("StxString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubMode {
            get {
                return this.SubModeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubModeField, value) != true)) {
                    this.SubModeField = value;
                    this.RaisePropertyChanged("SubMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmissionStatus {
            get {
                return this.SubmissionStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmissionStatusField, value) != true)) {
                    this.SubmissionStatusField = value;
                    this.RaisePropertyChanged("SubmissionStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Swl {
            get {
                return this.SwlField;
            }
            set {
                if ((object.ReferenceEquals(this.SwlField, value) != true)) {
                    this.SwlField = value;
                    this.RaisePropertyChanged("Swl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TenTen {
            get {
                return this.TenTenField;
            }
            set {
                if ((this.TenTenField.Equals(value) != true)) {
                    this.TenTenField = value;
                    this.RaisePropertyChanged("TenTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TheClass {
            get {
                return this.TheClassField;
            }
            set {
                if ((object.ReferenceEquals(this.TheClassField, value) != true)) {
                    this.TheClassField = value;
                    this.RaisePropertyChanged("TheClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TheOperator {
            get {
                return this.TheOperatorField;
            }
            set {
                if ((object.ReferenceEquals(this.TheOperatorField, value) != true)) {
                    this.TheOperatorField = value;
                    this.RaisePropertyChanged("TheOperator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeOff {
            get {
                return this.TimeOffField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeOffField, value) != true)) {
                    this.TimeOffField = value;
                    this.RaisePropertyChanged("TimeOff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeOn {
            get {
                return this.TimeOnField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeOnField, value) != true)) {
                    this.TimeOnField = value;
                    this.RaisePropertyChanged("TimeOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TxPwrDecimal {
            get {
                return this.TxPwrDecimalField;
            }
            set {
                if ((this.TxPwrDecimalField.Equals(value) != true)) {
                    this.TxPwrDecimalField = value;
                    this.RaisePropertyChanged("TxPwrDecimal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsacaCounties {
            get {
                return this.UsacaCountiesField;
            }
            set {
                if ((object.ReferenceEquals(this.UsacaCountiesField, value) != true)) {
                    this.UsacaCountiesField = value;
                    this.RaisePropertyChanged("UsacaCounties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ValidatedCallsign {
            get {
                return this.ValidatedCallsignField;
            }
            set {
                if ((this.ValidatedCallsignField.Equals(value) != true)) {
                    this.ValidatedCallsignField = value;
                    this.RaisePropertyChanged("ValidatedCallsign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VuccGrids {
            get {
                return this.VuccGridsField;
            }
            set {
                if ((object.ReferenceEquals(this.VuccGridsField, value) != true)) {
                    this.VuccGridsField = value;
                    this.RaisePropertyChanged("VuccGrids");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QsoAction", Namespace="http://schemas.datacontract.org/2004/07/LogOM.BE")]
    public enum QsoAction : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nothing = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Insert = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="log4omService.IWCFService")]
    public interface IWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/ConnectionTest", ReplyAction="http://tempuri.org/IWCFService/ConnectionTestResponse")]
        bool ConnectionTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/ConnectionTest", ReplyAction="http://tempuri.org/IWCFService/ConnectionTestResponse")]
        System.Threading.Tasks.Task<bool> ConnectionTestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetQslList", ReplyAction="http://tempuri.org/IWCFService/GetQslListResponse")]
        log4om.log4omService.Log GetQslList(string qslSent, string qslSentVia, int start, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetQslList", ReplyAction="http://tempuri.org/IWCFService/GetQslListResponse")]
        System.Threading.Tasks.Task<log4om.log4omService.Log> GetQslListAsync(string qslSent, string qslSentVia, int start, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetQslAdif", ReplyAction="http://tempuri.org/IWCFService/GetQslAdifResponse")]
        string GetQslAdif(string qslSent, string qslSentVia, int start, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetQslAdif", ReplyAction="http://tempuri.org/IWCFService/GetQslAdifResponse")]
        System.Threading.Tasks.Task<string> GetQslAdifAsync(string qslSent, string qslSentVia, int start, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/UpdateQSO", ReplyAction="http://tempuri.org/IWCFService/UpdateQSOResponse")]
        bool UpdateQSO(string adif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/UpdateQSO", ReplyAction="http://tempuri.org/IWCFService/UpdateQSOResponse")]
        System.Threading.Tasks.Task<bool> UpdateQSOAsync(string adif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/EditQSO", ReplyAction="http://tempuri.org/IWCFService/EditQSOResponse")]
        bool EditQSO(long qsoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/EditQSO", ReplyAction="http://tempuri.org/IWCFService/EditQSOResponse")]
        System.Threading.Tasks.Task<bool> EditQSOAsync(long qsoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/AddQSO", ReplyAction="http://tempuri.org/IWCFService/AddQSOResponse")]
        bool AddQSO(string adif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/AddQSO", ReplyAction="http://tempuri.org/IWCFService/AddQSOResponse")]
        System.Threading.Tasks.Task<bool> AddQSOAsync(string adif);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFServiceChannel : log4om.log4omService.IWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFServiceClient : System.ServiceModel.ClientBase<log4om.log4omService.IWCFService>, log4om.log4omService.IWCFService {
        
        public WCFServiceClient() {
        }
        
        public WCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ConnectionTest() {
            return base.Channel.ConnectionTest();
        }
        
        public System.Threading.Tasks.Task<bool> ConnectionTestAsync() {
            return base.Channel.ConnectionTestAsync();
        }
        
        public log4om.log4omService.Log GetQslList(string qslSent, string qslSentVia, int start, int count) {
            return base.Channel.GetQslList(qslSent, qslSentVia, start, count);
        }
        
        public System.Threading.Tasks.Task<log4om.log4omService.Log> GetQslListAsync(string qslSent, string qslSentVia, int start, int count) {
            return base.Channel.GetQslListAsync(qslSent, qslSentVia, start, count);
        }
        
        public string GetQslAdif(string qslSent, string qslSentVia, int start, int count) {
            return base.Channel.GetQslAdif(qslSent, qslSentVia, start, count);
        }
        
        public System.Threading.Tasks.Task<string> GetQslAdifAsync(string qslSent, string qslSentVia, int start, int count) {
            return base.Channel.GetQslAdifAsync(qslSent, qslSentVia, start, count);
        }
        
        public bool UpdateQSO(string adif) {
            return base.Channel.UpdateQSO(adif);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateQSOAsync(string adif) {
            return base.Channel.UpdateQSOAsync(adif);
        }
        
        public bool EditQSO(long qsoId) {
            return base.Channel.EditQSO(qsoId);
        }
        
        public System.Threading.Tasks.Task<bool> EditQSOAsync(long qsoId) {
            return base.Channel.EditQSOAsync(qsoId);
        }
        
        public bool AddQSO(string adif) {
            return base.Channel.AddQSO(adif);
        }
        
        public System.Threading.Tasks.Task<bool> AddQSOAsync(string adif) {
            return base.Channel.AddQSOAsync(adif);
        }
    }
}
